name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

  push:
    paths:
      - ".github/workflows/*"
      - "src/*"
      - "tests/*"
      - "pyproject.toml"
      - "setup.py"

  pull_request:
    paths:
      - "src/*"
      - "tests/*"
      - "pyproject.toml"
      - "setup.py"

env:
  SDCC_VERSION: 4.4.0

jobs:

  Build_Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install SDCC
        run: |
          cd ~
          wget https://sourceforge.net/projects/sdcc/files/sdcc-linux-amd64/$SDCC_VERSION/sdcc-$SDCC_VERSION-amd64-unknown-linux2.5.tar.bz2/download -O sdcc-amd64.tar.bz2
          sudo tar xf sdcc-amd64.tar.bz2
          cd sdcc-$SDCC_VERSION/
          sudo cp -r * /usr/local
          sdcc --version
          sdcc --print-search-dirs

      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd src
          make clean
          make CFLAGS=--Werror -j4

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: bin/main.hex

  Tests:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install "pycparser<3"
          pip install -e .
          pip install --upgrade pytest-md-report
          pip install gcovr

      - name: Run tests
        env:
          REPORT_OUTPUT: md_report.md
        shell: bash
        run: |
          rm -f tests/sim/_tsdz2.cdef

          echo "REPORT_FILE=${REPORT_OUTPUT}" >> "$GITHUB_ENV"

          gcc -Wall -Wextra -Q --help=warning

          pytest --strict --coverage \
                 --md-report \
                 --md-report-flavor gfm \
                 --md-report-output "$REPORT_OUTPUT"

      - name: Output reports to the job summary
        if: always()
        shell: bash
        run: |
          if [ -f "$REPORT_FILE" ]; then
            echo "## Test Report" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          else
            echo "Report file not found."
          fi

      - name: Render the report to the PR when tests fail
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-report
          recreate: true
          path: ${{ env.REPORT_FILE }}

      - name: Collect coverage data
        run: |
          echo "### Coverage Report" >> $GITHUB_STEP_SUMMARY
          gcovr -r tests --print-summary >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: tests/coverage_report.html
